/* Generated By:JavaCC: Do not edit this line. PUMLParserConstants.java */
package org.tutorial.pumllexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PUMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int START_UML = 8;
  /** RegularExpression Id. */
  int END_UML = 9;
  /** RegularExpression Id. */
  int AS = 10;
  /** RegularExpression Id. */
  int ALSO = 11;
  /** RegularExpression Id. */
  int AUTO_NUMBER = 12;
  /** RegularExpression Id. */
  int TITLE = 13;
  /** RegularExpression Id. */
  int NEW_PAGE = 14;
  /** RegularExpression Id. */
  int BOX = 15;
  /** RegularExpression Id. */
  int ALT = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int OPT = 18;
  /** RegularExpression Id. */
  int LOOP = 19;
  /** RegularExpression Id. */
  int PAR = 20;
  /** RegularExpression Id. */
  int BREAK = 21;
  /** RegularExpression Id. */
  int CRITICAL = 22;
  /** RegularExpression Id. */
  int NOTE = 23;
  /** RegularExpression Id. */
  int GROUP = 24;
  /** RegularExpression Id. */
  int LEFT = 25;
  /** RegularExpression Id. */
  int RIGHT = 26;
  /** RegularExpression Id. */
  int OF = 27;
  /** RegularExpression Id. */
  int ON = 28;
  /** RegularExpression Id. */
  int LINK = 29;
  /** RegularExpression Id. */
  int OVER = 30;
  /** RegularExpression Id. */
  int END = 31;
  /** RegularExpression Id. */
  int ACTIVATE = 32;
  /** RegularExpression Id. */
  int DEACTIVATE = 33;
  /** RegularExpression Id. */
  int DESTROY = 34;
  /** RegularExpression Id. */
  int CREATE = 35;
  /** RegularExpression Id. */
  int FOOTBOX = 36;
  /** RegularExpression Id. */
  int HIDE = 37;
  /** RegularExpression Id. */
  int SHOW = 38;
  /** RegularExpression Id. */
  int SKIN_PARAM = 39;
  /** RegularExpression Id. */
  int SKIN = 40;
  /** RegularExpression Id. */
  int TOP = 41;
  /** RegularExpression Id. */
  int BOTTOM = 42;
  /** RegularExpression Id. */
  int TOP_TO_BOTTOM_DIRECTION = 43;
  /** RegularExpression Id. */
  int PACKAGE = 44;
  /** RegularExpression Id. */
  int NAMESPACE = 45;
  /** RegularExpression Id. */
  int PAGE = 46;
  /** RegularExpression Id. */
  int UP = 47;
  /** RegularExpression Id. */
  int DOWN = 48;
  /** RegularExpression Id. */
  int IF = 49;
  /** RegularExpression Id. */
  int ENDIF = 50;
  /** RegularExpression Id. */
  int PARTITION = 51;
  /** RegularExpression Id. */
  int FOOTER = 52;
  /** RegularExpression Id. */
  int HEADER = 53;
  /** RegularExpression Id. */
  int CENTER = 54;
  /** RegularExpression Id. */
  int ROTATE = 55;
  /** RegularExpression Id. */
  int REF = 56;
  /** RegularExpression Id. */
  int RETURN = 57;
  /** RegularExpression Id. */
  int IS = 58;
  /** RegularExpression Id. */
  int REPEAT = 59;
  /** RegularExpression Id. */
  int START = 60;
  /** RegularExpression Id. */
  int STOP = 61;
  /** RegularExpression Id. */
  int WHILE = 62;
  /** RegularExpression Id. */
  int ENDWHILE = 63;
  /** RegularExpression Id. */
  int FORK = 64;
  /** RegularExpression Id. */
  int AGAIN = 65;
  /** RegularExpression Id. */
  int IDENTIFIER = 66;
  /** RegularExpression Id. */
  int LETTER = 67;
  /** RegularExpression Id. */
  int PART_LETTER = 68;
  /** RegularExpression Id. */
  int FORWARD_CALL_MESSAGE = 69;
  /** RegularExpression Id. */
  int FORWARD_CALL_DOTTED_MESSAGE = 70;
  /** RegularExpression Id. */
  int REVERSE_CALL_MESSAGE = 71;
  /** RegularExpression Id. */
  int REVERSE_CALL_DOTTED_MESSAGE = 72;
  /** RegularExpression Id. */
  int FORWARD_ASYNCHRONOUS_CALL_MESSAGE = 73;
  /** RegularExpression Id. */
  int REVERSE_ASYNCHRONOUS_CALL_MESSAGE = 74;
  /** RegularExpression Id. */
  int COLON_MESSAGE = 75;

    /**
    * Types
    */
   int ACTOR = 76;
   int PARTICIPANT = 77;
   int USECASE = 78;
   int CLASS = 79;
   int INTERFACE = 80;
   int ABSTRACT = 81;
   int ENUM = 82;
   int COMPONENT = 83;
   int STATE = 84;
   int OBJECT = 85;
  
  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/\\\'\"",
    "<SINGLE_LINE_COMMENT>",
    "\"\\\'/\"",
    "\"\\\'/\"",
    "<token of kind 7>",
    "\"@startuml\"",
    "\"@enduml\"",
    "\"as\"",
    "\"also\"",
    "\"autonumber\"",
    "\"title\"",
    "\"newpage\"",
    "\"box\"",
    "\"alt\"",
    "\"else\"",
    "\"opt\"",
    "\"loop\"",
    "\"par\"",
    "\"break\"",
    "\"critical\"",
    "\"note\"",
    "\"group\"",
    "\"left\"",
    "\"right\"",
    "\"of\"",
    "\"on\"",
    "\"link\"",
    "\"over\"",
    "\"end\"",
    "\"activate\"",
    "\"deactivate\"",
    "\"destroy\"",
    "\"create\"",
    "\"footbox\"",
    "\"hide\"",
    "\"show\"",
    "\"skinparam\"",
    "\"skin\"",
    "\"top\"",
    "\"bottom\"",
    "\"top to bottom direction\"",
    "\"package\"",
    "\"namespace\"",
    "\"page\"",
    "\"up\"",
    "\"down\"",
    "\"if\"",
    "\"endif\"",
    "\"partition\"",
    "\"footer\"",
    "\"header\"",
    "\"center\"",
    "\"rotate\"",
    "\"ref\"",
    "\"return\"",
    "\"is\"",
    "\"repeat\"",
    "\"start\"",
    "\"stop\"",
    "\"while\"",
    "\"endwhile\"",
    "\"fork\"",
    "\"again\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"->\"",
    "\"-->\"",
    "\"<-\"",
    "\"<--\"",
    "\"->>\"",
    "\"<<-\"",
    "\":\"",
    
    "\"actor\"",
    "\"participant\"",
    "\"usecase\"",
    "\"class\"",
    "\"interface\"",
    "\"abstract\"",
    "\"enum\"",
    "\"component\"",
    "\"state\"",
    "\"object\"",
  };

}
