/* Generated By:JavaCC: Do not edit this line. PUMLParserConstants.java */
package org.netbeans.modules.plantumlnb.pumllexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PUMLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int MESSAGE = 3;
  /** RegularExpression Id. */
  int START_UML = 4;
  /** RegularExpression Id. */
  int END_UML = 5;
  /** RegularExpression Id. */
  int AS = 6;
  /** RegularExpression Id. */
  int ALSO = 7;
  /** RegularExpression Id. */
  int AUTO_NUMBER = 8;
  /** RegularExpression Id. */
  int TITLE = 9;
  /** RegularExpression Id. */
  int NEW_PAGE = 10;
  /** RegularExpression Id. */
  int BOX = 11;
  /** RegularExpression Id. */
  int ALT = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int OPT = 14;
  /** RegularExpression Id. */
  int LOOP = 15;
  /** RegularExpression Id. */
  int PAR = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int CRITICAL = 18;
  /** RegularExpression Id. */
  int NOTE = 19;
  /** RegularExpression Id. */
  int GROUP = 20;
  /** RegularExpression Id. */
  int LEFT = 21;
  /** RegularExpression Id. */
  int RIGHT = 22;
  /** RegularExpression Id. */
  int OF = 23;
  /** RegularExpression Id. */
  int ON = 24;
  /** RegularExpression Id. */
  int LINK = 25;
  /** RegularExpression Id. */
  int OVER = 26;
  /** RegularExpression Id. */
  int END = 27;
  /** RegularExpression Id. */
  int ACTIVATE = 28;
  /** RegularExpression Id. */
  int DEACTIVATE = 29;
  /** RegularExpression Id. */
  int DESTROY = 30;
  /** RegularExpression Id. */
  int CREATE = 31;
  /** RegularExpression Id. */
  int FOOTBOX = 32;
  /** RegularExpression Id. */
  int HIDE = 33;
  /** RegularExpression Id. */
  int SHOW = 34;
  /** RegularExpression Id. */
  int SKIN_PARAM = 35;
  /** RegularExpression Id. */
  int SKIN = 36;
  /** RegularExpression Id. */
  int TOP = 37;
  /** RegularExpression Id. */
  int BOTTOM = 38;
  /** RegularExpression Id. */
  int TOP_TO_BOTTOM_DIRECTION = 39;
  /** RegularExpression Id. */
  int PACKAGE = 40;
  /** RegularExpression Id. */
  int NAMESPACE = 41;
  /** RegularExpression Id. */
  int PAGE = 42;
  /** RegularExpression Id. */
  int UP = 43;
  /** RegularExpression Id. */
  int DOWN = 44;
  /** RegularExpression Id. */
  int IF = 45;
  /** RegularExpression Id. */
  int ENDIF = 46;
  /** RegularExpression Id. */
  int PARTITION = 47;
  /** RegularExpression Id. */
  int FOOTER = 48;
  /** RegularExpression Id. */
  int HEADER = 49;
  /** RegularExpression Id. */
  int CENTER = 50;
  /** RegularExpression Id. */
  int ROTATE = 51;
  /** RegularExpression Id. */
  int REF = 52;
  /** RegularExpression Id. */
  int RETURN = 53;
  /** RegularExpression Id. */
  int IS = 54;
  /** RegularExpression Id. */
  int REPEAT = 55;
  /** RegularExpression Id. */
  int START = 56;
  /** RegularExpression Id. */
  int STOP = 57;
  /** RegularExpression Id. */
  int WHILE = 58;
  /** RegularExpression Id. */
  int ENDWHILE = 59;
  /** RegularExpression Id. */
  int FORK = 60;
  /** RegularExpression Id. */
  int AGAIN = 61;
  /** RegularExpression Id. */
  int FORWARD_CALL_MESSAGE = 62;
  /** RegularExpression Id. */
  int FORWARD_CALL_DOTTED_MESSAGE = 63;
  /** RegularExpression Id. */
  int REVERSE_CALL_MESSAGE = 64;
  /** RegularExpression Id. */
  int REVERSE_CALL_DOTTED_MESSAGE = 65;
  /** RegularExpression Id. */
  int FORWARD_ASYNCHRONOUS_CALL_MESSAGE = 66;
  /** RegularExpression Id. */
  int REVERSE_ASYNCHRONOUS_CALL_MESSAGE = 67;
  /** RegularExpression Id. */
  int DOTS_DASHES = 68;
  /** RegularExpression Id. */
  int LEFT_COMPOSITION = 69;
  /** RegularExpression Id. */
  int RIGHT_COMPOSITION = 70;
  /** RegularExpression Id. */
  int ACTOR = 71;
  /** RegularExpression Id. */
  int PARTICIPANT = 72;
  /** RegularExpression Id. */
  int USECASE = 73;
  /** RegularExpression Id. */
  int CLASS = 74;
  /** RegularExpression Id. */
  int INTERFACE = 75;
  /** RegularExpression Id. */
  int ABSTRACT = 76;
  /** RegularExpression Id. */
  int ENUM = 77;
  /** RegularExpression Id. */
  int COMPONENT = 78;
  /** RegularExpression Id. */
  int STATE = 79;
  /** RegularExpression Id. */
  int OBJECT = 80;
  /** RegularExpression Id. */
  int ARTIFACT = 81;
  /** RegularExpression Id. */
  int FOLDER = 82;
  /** RegularExpression Id. */
  int RECT = 83;
  /** RegularExpression Id. */
  int NODE = 84;
  /** RegularExpression Id. */
  int FRAME = 85;
  /** RegularExpression Id. */
  int CLOUD = 86;
  /** RegularExpression Id. */
  int DATABASE = 87;
  /** RegularExpression Id. */
  int STORAGE = 88;
  /** RegularExpression Id. */
  int AGENT = 89;
  /** RegularExpression Id. */
  int BOUNDARY = 90;
  /** RegularExpression Id. */
  int CONTROL = 91;
  /** RegularExpression Id. */
  int ENTITY = 92;
  /** RegularExpression Id. */
  int IDENTIFIER = 93;
  /** RegularExpression Id. */
  int LETTER = 94;
  /** RegularExpression Id. */
  int PART_LETTER = 95;

  /** Lexical state. */
  int DEFAULT = 96;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "<MESSAGE>",
    "\"@startuml\"",
    "\"@enduml\"",
    "\"as\"",
    "\"also\"",
    "\"autonumber\"",
    "\"title\"",
    "\"newpage\"",
    "\"box\"",
    "\"alt\"",
    "\"else\"",
    "\"opt\"",
    "\"loop\"",
    "\"par\"",
    "\"break\"",
    "\"critical\"",
    "\"note\"",
    "\"group\"",
    "\"left\"",
    "\"right\"",
    "\"of\"",
    "\"on\"",
    "\"link\"",
    "\"over\"",
    "\"end\"",
    "\"activate\"",
    "\"deactivate\"",
    "\"destroy\"",
    "\"create\"",
    "\"footbox\"",
    "\"hide\"",
    "\"show\"",
    "\"skinparam\"",
    "\"skin\"",
    "\"top\"",
    "\"bottom\"",
    "\"top to bottom direction\"",
    "\"package\"",
    "\"namespace\"",
    "\"page\"",
    "\"up\"",
    "\"down\"",
    "\"if\"",
    "\"endif\"",
    "\"partition\"",
    "\"footer\"",
    "\"header\"",
    "\"center\"",
    "\"rotate\"",
    "\"ref\"",
    "\"return\"",
    "\"is\"",
    "\"repeat\"",
    "\"start\"",
    "\"stop\"",
    "\"while\"",
    "\"endwhile\"",
    "\"fork\"",
    "\"again\"",
    "\"->\"",
    "\"-->\"",
    "\"<-\"",
    "\"<--\"",
    "\"->>\"",
    "\"<<-\"",
    "<DOTS_DASHES>",
    "<LEFT_COMPOSITION>",
    "<RIGHT_COMPOSITION>",
    "\"actor\"",
    "\"participant\"",
    "\"usecase\"",
    "\"class\"",
    "\"interface\"",
    "\"abstract\"",
    "\"enum\"",
    "\"component\"",
    "\"state\"",
    "\"object\"",
    "\"artifact\"",
    "\"folder\"",
    "\"rect\"",
    "\"node\"",
    "\"frame\"",
    "\"cloud\"",
    "\"database\"",
    "\"storage\"",
    "\"agent\"",
    "\"boundary\"",
    "\"control\"",
    "\"entity\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<token of kind 96>",
  };

}
