/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.plantumlnb.ui.wizard;

import javax.swing.JPanel;

public final class PlantUMLVisualPanel5 extends JPanel {

    /**
     * Creates new form PlantUMLVisualPanel4
     */
    public PlantUMLVisualPanel5() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Enter display name regular expressions";
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPackageNameTextExpressionScrollPane = new javax.swing.JScrollPane();
        displayPackageNameTextExpressionArea = new javax.swing.JTextArea();
        displayPackageNameExamplesLabel = new javax.swing.JLabel();
        displayPackageNameTitle = new javax.swing.JLabel();

        displayPackageNameTextExpressionArea.setColumns(20);
        displayPackageNameTextExpressionArea.setRows(5);
        displayPackageNameTextExpressionScrollPane.setViewportView(displayPackageNameTextExpressionArea);

        displayPackageNameExamplesLabel.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(displayPackageNameExamplesLabel, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel5.class, "PlantUMLVisualPanel5.displayPackageNameExamplesLabel.text_3")); // NOI18N
        displayPackageNameExamplesLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.openide.awt.Mnemonics.setLocalizedText(displayPackageNameTitle, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel5.class, "PlantUMLVisualPanel5.displayPackageNameTitle.text")); // NOI18N
        displayPackageNameTitle.setToolTipText(org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel5.class, "PlantUMLVisualPanel5.displayPackageNameTitle.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPackageNameExamplesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(displayPackageNameTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayPackageNameTextExpressionScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPackageNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayPackageNameTextExpressionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayPackageNameExamplesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayPackageNameExamplesLabel;
    private javax.swing.JTextArea displayPackageNameTextExpressionArea;
    private javax.swing.JScrollPane displayPackageNameTextExpressionScrollPane;
    private javax.swing.JLabel displayPackageNameTitle;
    // End of variables declaration//GEN-END:variables

    public String getDisplayNameRegex() {
        return displayPackageNameTextExpressionArea.getText();
    }

}
