/* 
 * The MIT License
 *
 * Copyright 2017 Venkat Ram Akkineni.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.netbeans.modules.plantumlnb.ui.wizard;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;

public final class PlantUMLVisualPanel5 extends JPanel implements GenericDocumentListener,
        Initializable<PlantUMLWizardPanel5>, GenericChangeListener {

    private PlantUMLWizardPanel5 plantUMLWizardPanel5;

    private final List<ChangeListener> listeners = new ArrayList<>();

    /**
     * Creates new form PlantUMLVisualPanel5
     */
    public PlantUMLVisualPanel5() {
        initComponents();
    }
    
    @Override
    public void init(PlantUMLWizardPanel5 plantUMLWizardPanel5) {
        this.plantUMLWizardPanel5 = plantUMLWizardPanel5;
        
        displayNameTextExpressionArea.getDocument().addDocumentListener(this);
    }

    @Override
    public String getName() {
        return "Enter display name regular expressions";
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayNameTextExpressionScrollPane = new javax.swing.JScrollPane();
        displayNameTextExpressionArea = new javax.swing.JTextArea();
        displayNameExamplesLabel = new javax.swing.JLabel();
        displayNameTitle = new javax.swing.JLabel();

        displayNameTextExpressionArea.setColumns(20);
        displayNameTextExpressionArea.setRows(5);
        displayNameTextExpressionScrollPane.setViewportView(displayNameTextExpressionArea);

        displayNameExamplesLabel.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(displayNameExamplesLabel, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel5.class, "PlantUMLVisualPanel5.displayNameExamplesLabel.text_3")); // NOI18N
        displayNameExamplesLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        org.openide.awt.Mnemonics.setLocalizedText(displayNameTitle, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel5.class, "PlantUMLVisualPanel5.displayNameTitle.text")); // NOI18N
        displayNameTitle.setToolTipText(org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel5.class, "PlantUMLVisualPanel5.displayNameTitle.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayNameExamplesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(displayNameTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayNameTextExpressionScrollPane, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayNameTextExpressionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayNameExamplesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayNameExamplesLabel;
    private javax.swing.JTextArea displayNameTextExpressionArea;
    private javax.swing.JScrollPane displayNameTextExpressionScrollPane;
    private javax.swing.JLabel displayNameTitle;
    // End of variables declaration//GEN-END:variables

    public String getDisplayNameRegex() {
        return displayNameTextExpressionArea.getText();
    }

    @Override
    public void updateUI(DocumentEvent e) {
        
    }

    @Override
    public ValidatingWizardPanel getValidatingWizardPanel() {
        return plantUMLWizardPanel5;
    }

    public static PlantUMLVisualPanel5 createInstance(final PlantUMLWizardPanel5 plantUMLWizardPanel5) {
        PlantUMLVisualPanel5 plantUMLVisualPanel5 = new PlantUMLVisualPanel5();
        plantUMLVisualPanel5.init(plantUMLWizardPanel5);
        return plantUMLVisualPanel5;
    }

    @Override
    public List<ChangeListener> getChangeListeners() {
        return listeners;
    }
}
