/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.plantumlnb.ui.wizard;

import javax.swing.JPanel;

public final class PlantUMLVisualPanel4 extends JPanel {

    /**
     * Creates new form PlantUMLVisualPanel4
     */
    public PlantUMLVisualPanel4() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Enter display package name regular expressions";
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayPackageNameTextExpressionScrollPane1 = new javax.swing.JScrollPane();
        displayPackageNameTextExpressionArea1 = new javax.swing.JTextArea();
        displayPackageNameTitle3 = new javax.swing.JLabel();
        displayPackageNameTitle4 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        displayPackageNameTextExpressionArea1.setColumns(20);
        displayPackageNameTextExpressionArea1.setRows(5);
        displayPackageNameTextExpressionScrollPane1.setViewportView(displayPackageNameTextExpressionArea1);

        displayPackageNameTitle3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(displayPackageNameTitle3, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel4.class, "PlantUMLVisualPanel4.displayPackageNameTitle3.text")); // NOI18N
        displayPackageNameTitle3.setToolTipText(org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel4.class, "PlantUMLVisualPanel4.displayPackageNameTitle3.toolTipText")); // NOI18N

        displayPackageNameTitle4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(displayPackageNameTitle4, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel4.class, "PlantUMLVisualPanel4.displayPackageNameTitle4.text")); // NOI18N
        displayPackageNameTitle4.setToolTipText(org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel4.class, "PlantUMLVisualPanel4.displayPackageNameTitle4.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPackageNameTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayPackageNameTextExpressionScrollPane1)
                    .addComponent(displayPackageNameTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPackageNameTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayPackageNameTextExpressionScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayPackageNameTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displayPackageNameTextExpressionArea1;
    private javax.swing.JScrollPane displayPackageNameTextExpressionScrollPane1;
    private javax.swing.JLabel displayPackageNameTitle3;
    private javax.swing.JLabel displayPackageNameTitle4;
    // End of variables declaration//GEN-END:variables

}
