/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.plantumlnb.ui.wizard;

import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public final class PlantUMLVisualPanel1 extends JPanel {
    
    private PlantUMLWizardPanel1 plantUMLWizardPanel1;

    /**
     * Creates new form PlantUMLVisualPanel1
     */
    public PlantUMLVisualPanel1(PlantUMLWizardPanel1 plantUMLWizardPanel1) {
        initComponents();
        
        this.plantUMLWizardPanel1 = plantUMLWizardPanel1;
        
        getPlantumlFileNameTextField().getDocument().addDocumentListener(new GenericDocumentListener());
        getPackageSelectionInputDirectory().getDocument().addDocumentListener(new GenericDocumentListener());
        getDestinationDirectoryTextField().getDocument().addDocumentListener(new GenericDocumentListener());
    }

    @Override
    public String getName() {
        return "Choose a source package";
    }

    @Override
    public void validate() {
        super.validate();         
    }
    
    public void updateUI(DocumentEvent e) {
        if (getPlantumlFileNameTextField().getDocument() == e.getDocument()) {
            firePropertyChange(DESTINATION_DIRECTORY, null, destinationDirectoryTextField.getText());
        }
        if (getPackageSelectionInputDirectory().getDocument() == e.getDocument()) {
            firePropertyChange(PLANTUML_FILE_NAME, null, plantumlFileNameTextField.getText());
        }
        if (getPackageSelectionInputDirectory().getDocument() == e.getDocument()) {
            firePropertyChange(PACKAGE_SELECTION, null, packageSelectionInputDirectory.getText());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        existingSourcesPaneLabel = new javax.swing.JLabel();
        packageSelectionButton = new javax.swing.JButton();
        packageSelectionInputDirectory = new javax.swing.JTextField();
        plantumlFileNameTextField = new javax.swing.JTextField();
        destinationDirectoryTextField = new javax.swing.JTextField();
        destinationDirectoryButton = new javax.swing.JButton();
        pumlFileNameLabel = new javax.swing.JLabel();
        generatedFileNameLabel = new javax.swing.JLabel();
        packageSelectionLabel = new javax.swing.JLabel();
        destinationDirectoryLabel = new javax.swing.JLabel();
        generatedFileNameDisplayTextField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(existingSourcesPaneLabel, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.existingSourcesPaneLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(packageSelectionButton, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.packageSelectionButton.text")); // NOI18N

        packageSelectionInputDirectory.setText(org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.packageSelectionInputDirectory.text")); // NOI18N

        plantumlFileNameTextField.setText(org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.plantumlFileNameTextField.text")); // NOI18N
        plantumlFileNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                updateGeneratedFileNameDisplayLabel(evt);
            }
        });

        destinationDirectoryTextField.setText(org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.destinationDirectoryTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(destinationDirectoryButton, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.destinationDirectoryButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(pumlFileNameLabel, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.pumlFileNameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(generatedFileNameLabel, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.generatedFileNameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(packageSelectionLabel, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.packageSelectionLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(destinationDirectoryLabel, org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.destinationDirectoryLabel.text")); // NOI18N

        generatedFileNameDisplayTextField.setEditable(false);
        generatedFileNameDisplayTextField.setText(org.openide.util.NbBundle.getMessage(PlantUMLVisualPanel1.class, "PlantUMLVisualPanel1.generatedFileNameDisplayTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generatedFileNameDisplayTextField)
                    .addComponent(existingSourcesPaneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plantumlFileNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generatedFileNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(packageSelectionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destinationDirectoryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(destinationDirectoryTextField)
                        .addGap(18, 18, 18)
                        .addComponent(destinationDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(packageSelectionInputDirectory)
                        .addGap(18, 18, 18)
                        .addComponent(packageSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pumlFileNameLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(existingSourcesPaneLabel)
                .addGap(18, 18, 18)
                .addComponent(pumlFileNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plantumlFileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generatedFileNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generatedFileNameDisplayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(destinationDirectoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationDirectoryButton)
                    .addComponent(destinationDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(packageSelectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageSelectionInputDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packageSelectionButton))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateGeneratedFileNameDisplayLabel(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateGeneratedFileNameDisplayLabel
        generatedFileNameDisplayTextField.setText(plantumlFileNameTextField.getText() + ".puml");
    }//GEN-LAST:event_updateGeneratedFileNameDisplayLabel

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton destinationDirectoryButton;
    private javax.swing.JLabel destinationDirectoryLabel;
    private javax.swing.JTextField destinationDirectoryTextField;
    private javax.swing.JLabel existingSourcesPaneLabel;
    private javax.swing.JTextField generatedFileNameDisplayTextField;
    private javax.swing.JLabel generatedFileNameLabel;
    private javax.swing.JButton packageSelectionButton;
    private javax.swing.JTextField packageSelectionInputDirectory;
    private javax.swing.JLabel packageSelectionLabel;
    private javax.swing.JTextField plantumlFileNameTextField;
    private javax.swing.JLabel pumlFileNameLabel;
    // End of variables declaration//GEN-END:variables

    private static final String DESTINATION_DIRECTORY = "destinationDirectoryTextField";
    private static final String PLANTUML_FILE_NAME = "plantumlFileNameTextField"; 
    private static final String PACKAGE_SELECTION = "packageSelectionInputDirectory";
    
    
    public JTextField getDestinationDirectoryTextField() {
        return destinationDirectoryTextField;
    }

    public void setDestinationDirectoryTextField(JTextField destinationDirectoryTextField) {
        this.destinationDirectoryTextField = destinationDirectoryTextField;
    }

    public JTextField getPackageSelectionInputDirectory() {
        return packageSelectionInputDirectory;
    }

    public void setPackageSelectionInputDirectory(JTextField packageSelectionInputDirectory) {
        this.packageSelectionInputDirectory = packageSelectionInputDirectory;
    }

    public JTextField getPlantumlFileNameTextField() {
        return plantumlFileNameTextField;
    }

    public void setPlantumlFileNameTextField(JTextField plantumlFileNameTextField) {
        this.plantumlFileNameTextField = plantumlFileNameTextField;
    }
    
    
    class GenericDocumentListener implements DocumentListener {
        
        @Override
        public void insertUpdate(DocumentEvent e) {
            plantUMLWizardPanel1.fireChangeEvent();
            updateUI();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            plantUMLWizardPanel1.fireChangeEvent();
            updateUI();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            plantUMLWizardPanel1.fireChangeEvent();
            updateUI();
        }
        
    }

}
